-------------------------------------------------------------------------------
-- Copyright Lancelot SIX                                                    --
--                                                                           --
-- lancelot@lancelotsix.com                                                  --
--                                                                           --
-- This software is governed by the CeCILL license under French law and      --
-- abiding by the rules of distribution of free software.  You can  use,     --
-- modify and/ or redistribute the software under the terms of the CeCILL    --
-- license as circulated by CEA, CNRS and INRIA at the following URL         --
-- "http://www.cecill.info".                                                 --
--                                                                           --
-- As a counterpart to the access to the source code and  rights to copy,    --
-- modify and redistribute granted by the license, users are provided only   --
-- with a limited warranty  and the software's author,  the holder of the    --
-- economic rights,  and the successive licensors  have only  limited        --
-- liability.                                                                --
--                                                                           --
-- In this respect, the user's attention is drawn to the risks associated    --
-- with loading,  using,  modifying and/or developing or reproducing the     --
-- software by the user in light of its specific status of free software,    --
-- that may mean  that it is complicated to manipulate,  and  that  also     --
-- therefore means  that it is reserved for developers  and  experienced     --
-- professionals having in-depth computer knowledge. Users are therefore     --
-- encouraged to load and test the software's suitability as regards their   --
-- requirements in conditions enabling the security of their systems and/or  --
-- data to be ensured and,  more generally, to use and operate it in the     --
-- same conditions as regards security.                                      --
--                                                                           --
-- The fact that you are presently reading this means that you have had      --
-- knowledge of the CeCILL license and that you accept its terms.            --

with Ada.Directories;

use all type Ada.Directories.File_Kind;

-- This package provides primitives to deal with file attribute as generated by
-- JabRef
-- In bibtex, file references are encoded as follows :
-- file = :{<some_path>:<file_type>}
-- where some_path is a backslashed excapted string.
package File_Attribute_Helper is

   -- Check wether the string represent a valid representation of a file
   -- attribute as proposed by JabRef
   -- Checks that the string has the format :<some_path>:<some_format>
   -- Absolutly no assumption is done on the content of the path and format
   -- information. Only the columns are checked.
   function Is_Valid_File_Attribute(Str : String) return Boolean;

   -- Return the path contained in an attribute value
   function Get_Path(Str : String) return String
   with Precondition => Is_Valid_File_Attribute(Str);

   -- Return the file format described in the file pattern
   function Get_File_Format(Str : String) return String
   with Precondition => Is_Valid_File_Attribute(Str);

   -- Create a corect file_attribute value based on a file path ant a file
   -- format
   function Build_File_Attribute(File_Path   : String;
                                 File_Format : String) return String
     with Postcondition => Is_Valid_File_Attribute(Build_File_Attribute'Result);

   -- Finds the clothest math of Original_Path within
   -- Lookup_Path directory.
   function Find_File_Match(Original_Path : String;
                            Lookup_Path   : String) return String
   with Precondition => (Ada.Directories.Exists(Lookup_Path) and then
                           Ada.Directories.Kind(Lookup_Path) = Directory);

   -- Exception raised if the system cannot determine if a
   -- '/' or a '\' should be used on this system.
   Error_Determining_File_System_Type : exception;

   -- Exception raised when the desired file cannot be found in the
   -- specified directory
   Matching_File_Not_Found            : exception;

end File_Attribute_Helper;
